version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/server"
      - "/cli"
      - "/ramekin-core"
    schedule:
      interval: "weekly"
    groups:
      rust-deps:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/ramekin-ui"
    schedule:
      interval: "weekly"
    groups:
      npm-deps:
        patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
