---
version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/server"
      - "/cli"
      - "/ramekin-core"
      - "/ingredient-density"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "America/Los_Angeles"
    groups:
      rust-deps:
        patterns: ["*"]

  - package-ecosystem: "npm"
    directory: "/ramekin-ui"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "America/Los_Angeles"
    groups:
      npm-deps:
        patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "America/Los_Angeles"
